* Testni dan d-labs
  :LOGBOOK:
  CLOCK: [2017-11-14 Tue 09:52]
  :END:
** priprava
   - naredim uporabnika za mysql - ni potrebe - sem prečekiral setup.sql
   - stestiram setup
     - najbrž bo treba še nekje uporabnika in bazo prilagodit
*** naučim se simphony
    zgleda fino :)
** razvoj
   [2017-11-14 Tue 10:25]
   - Dokončat moram fajl src/Command/ReportYearlyCommand.php
     - izpisat mora lep report
   - raziščem bazo - ima 2 tabeli, v eni so profili, v drugi so podatki
   - naredim SQL query in potem z $io->table izpišem

** za narest
   - 5 test kejsov
     - robni pogoji
   - implementacija funkconalnosti

*** glavno
    - ko izvršim Yearly Views report -> mesečni pregled za posamezni profil
    - ko pogledam Yearly Views report -> profili razporejeni po abecednem
      vrstnem redu
    - ko pogledam Yearly Views report -> mora pisat "n/a" za mesece, ko podatki
      manjkajo

*** poizvedbe v bazo
    Za določeno leto, za določen profil, dobim različne mesece, več podatkov v
    enem mesecu. Za določen profil moram seštet podatke v enem mesecu. Kako bom
    hendlal datume? 

    Funkcija, ki prejme datum in profile_id in izračuna vsoto za en mesec.
    Skratka to je samo ena poizvedba:

    ~SELECT SUM(view) FROM views WHERE date="$month" AND profile_id=$pid;~

    Morda bi obstajal kak paket, ki močno olajša db poizvedbe. Ampak ne poznam
    paketa.

    Dobim tabelo profilov - asociativno polje pid in pname.

    Grem čez tabelo za posamezno leto, ki ima dvanajst mesecev in sevede delam
    seštevke. Zafiljujem še eno asociativno tabelo.

    Na koncu moram tabelo uredit po abecednem vrstem redu. 

    
**** lepa tabela uporabnikov
     imamo

**** gremo po mesecih
     [2017-11-14 Tue 11:52]
     tabela: pid => [mesec => sum(views)]

*** testi in optimizacija kode
    [2017-11-14 Tue 15:38] prišel z malice...

**** Robni pogoji
     - letnica je out of range (navzgor in navzdol)
     - 2016 je prestopno leto - februar ima 29 dni
     - ??? ni uporabnikov

**** testi
     1. Za mesece brez podatkov, se izpiše "n/a".
     2. Preveri, če koda upošteva, da je februar prestopni mesec.
     3. Scenario: year argument not given
        Notify user, he should call the console with year argument = print help.
     4. Check if the profile data correspodns with sum of monthly views for specific profile.
     
     Scenario: get report for year X
       Make SQL query for each month
       Write Monthly data in Yearly array
       Write Yearly data in Profile array
       Structure data that it will be suitable for output report
       Given that there is data for year X

     Scenario: year argument for report generation not given
       Throw exception - year argument is required

     This means that Not enough arguments exception - is a feature.
       
